export const projectionPageStyles = {
  container: {
      justifyContent: 'center',
      alignItems: 'center',
      padding: '3rem',
      fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
      color: '#f4f4f4',
      backgroundColor: '#2c2c2c',
      minHeight: '100vh',
  },
  header: {
      textAlign: 'center' as 'center',
      marginBottom: '3rem',
      backgroundColor: '#444',
      color: '#fff',
      padding: '2rem',
      borderRadius: '8px',
      boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
      width: '80%',
      margin: '0 auto',
  },
  headerTitle: {
      fontSize: '2.5rem',
      marginBottom: '1rem',
  },
  headerSubtitle: {
      fontSize: '1.25rem',
  },
  scheduleArea: {
      marginTop: '3rem',
      textAlign: 'center' as 'center',
      width: '90%',
      marginLeft: 'auto',
      marginRight: 'auto',
  },
  sectionTitle: {
      fontSize: '2rem',
      marginBottom: '1.5rem',
      color: '#ddd',
  },
  scheduleTable: {
      width: '100%',
      marginLeft: '2rem',
      borderCollapse: 'collapse' as 'collapse',
      backgroundColor: '#444',
      color: '#fff',
      borderRadius: '8px',
      overflow: 'hidden',
      boxShadow: '0 10px 20px rgba(0, 0, 0, 0.3)',
  },
  scheduleTableCell: {
      padding: '1.5rem',
      textAlign: 'center' as 'center',
      border: '2px solid #555',
      backgroundColor: '#333',
  },
  classBlockCell: {
      cursor: 'pointer',
      backgroundColor: '#666',
      color: '#fff',
      borderRadius: '8px',
      border: '2px solid #444',
      padding: '1rem',
      fontWeight: 'bold',
      transition: 'background-color 0.3s ease',
  },
  classBlockCellHover: {
      backgroundColor: '#777',
  },
  overlay: {
      position: 'fixed',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      backgroundColor: 'rgba(44, 44, 44, 0.95)',
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 1000,
  },
  overlayContent: {
      backgroundColor: '#333',
      padding: '2.5rem',
      borderRadius: '12px',
      color: '#f4f4f4',
      textAlign: 'center',
      boxShadow: '0 8px 20px rgba(0, 0, 0, 0.5)',
      width: '90%',
      maxWidth: '500px',
      animation: 'fadeIn 0.3s ease',
  },
  overlayHeader: {
      fontSize: '1.75rem',
      marginBottom: '1rem',
      color: '#fff',
  },
  overlayText: {
      fontSize: '1.2rem',
      marginBottom: '2rem',
  },
  overlayButton: {
      padding: '0.8rem 1.5rem',
      backgroundColor: '#444',
      color: '#fff',
      border: 'none',
      borderRadius: '8px',
      cursor: 'pointer',
      fontSize: '1rem',
      transition: 'background-color 0.3s ease',
  },
  overlayButtonHover: {
      backgroundColor: '#555',
  },
  error: {
      color: '#ff4d4d',
      fontWeight: 'bold',
      margin: '1rem 0',
      textAlign: 'center' as 'center',
  },
  preview: {
      marginTop: '2rem',
      backgroundColor: '#333',
      padding: '1.5rem',
      borderRadius: '8px',
      boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
      color: '#fff',
      width: '80%',
      marginLeft: 'auto',
      marginRight: 'auto',
  },
};
