export const projectionPageStyles = {
    container: {
        justifyContent: 'center',
        alignItems: 'center',
        fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
        color: '#f4f4f4',
        backgroundColor: '#2c2c2c',
        minHeight: '100vh',
    },
    header: {
        textAlign: 'center',
        marginBottom: '3rem',
        width: '100%',
        padding: '2rem',
        borderRadius: '8px',
        boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
        margin: '0 auto',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#333',
        color: '#fff',
        position: 'fixed',
        top: '0',
        borderBottom: '3px solid #555',
    },
    scheduleArea: {
        marginTop: '9rem',
        textAlign: 'center',
        width: '90%',
        marginLeft: 'auto',
        marginRight: 'auto',
    },
    scheduleTable: {
        width: '100%',
        marginLeft: '2rem',
        borderCollapse: 'collapse',
        backgroundColor: '#444',
        color: '#fff',
        borderRadius: '8px',
        overflow: 'hidden',
        boxShadow: '0 10px 20px rgba(0, 0, 0, 0.3)',
    },
    scheduleTableCell: {
        padding: '1.5rem',
        textAlign: 'center',
        border: '2px solid #555',
        backgroundColor: '#333',
    },
    error: {
        color: '#ff4d4d',
        fontWeight: 'bold',
        margin: '1rem 0',
        textAlign: 'center',
    },
    preview: {
        marginTop: '2rem',
        backgroundColor: '#333',
        padding: '1.5rem',
        borderRadius: '8px',
        boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
        color: '#fff',
        width: '80%',
        marginLeft: 'auto',
        marginRight: 'auto',
    },
    // New styles for buttons and combo box
    button: {
        padding: '0.8rem 2rem',
        backgroundColor: '#444',
        color: '#fff',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '1rem',
        fontWeight: 'bold',
        transition: 'background-color 0.3s ease',
        margin: '1rem',
        boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
    },
    buttonDisabled: {
        backgroundColor: '#888',
        color: '#ccc',
        cursor: 'not-allowed',
    },
    buttonHover: {
        backgroundColor: '#555',
    },
    selectBox: {
        padding: '0.5rem',
        fontSize: '1rem',
        borderRadius: '8px',
        border: '2px solid #555',
        backgroundColor: '#333',
        color: '#fff',
        width: '30%',
        boxShadow: '0 2px 5px rgba(0, 0, 0, 0.2)',
        marginTop: '1rem',
    },
    saveScheduleButton: {
        padding: '0.8rem 2rem',
        backgroundColor: '#28a745', // Verde para un botón de guardar
        color: '#fff',
        border: 'none',
        borderRadius: '8px',
        cursor: 'pointer',
        fontSize: '1rem',
        fontWeight: 'bold',
        transition: 'background-color 0.3s ease',
        margin: '1rem',
        boxShadow: '0 4px 8px rgba(0, 0, 0, 0.2)',
    },
    saveScheduleButtonDisabled: {
        backgroundColor: '#888', // Gris para el estado deshabilitado
        color: '#ccc',
        cursor: 'not-allowed',
    },
    saveScheduleButtonHover: {
        backgroundColor: '#218838', // Un verde más oscuro al hacer hover
    },
};
