export const homeStyles = {
	container: {
		justifyContent: 'center',
		alignItems: 'center',
		fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
		color: '#f4f4f4',
		backgroundColor: '#2c2c2c',
		height: '100vh',
	},
	header: {
		top: '0',
		width: '100%',
		borderBottom: '3px solid #555',
		marginBottom: '3rem',
		backgroundColor: '#444',
		color: '#fff',
		borderRadius: '8px',
		boxShadow: '0 4px 8px rgba(0, 0, 0, 0.3)',
		paddingTop: '2rem',
		paddingBottom: '2rem',
	},
	title: {
		display: 'flex',
		fontSize: '1.5rem',
		justifyContent: 'center',
	},
	loginContainer: {
		display: 'flex',
		justifyContent: 'right',
		marginRight: '2rem',
	},
	loginForm: {
		marginTop: '2rem',
	},
	input: {
		marginRight: '0.5rem',
		padding: '0.5rem',
		fontSize: '1rem',
		borderRadius: '4px',
		border: '1px solid #ccc',
	},
	button: {
		padding: '0.5rem 1rem',
		fontSize: '1rem',
		backgroundColor: '#666',
		color: '#fff',
		border: 'none',
		borderRadius: '4px',
		cursor: 'pointer',
	},
	schedulePreview: {
		marginTop: '3rem',
		marginBottom: '4rem',
		marginLeft: '2rem',
		marginRight: '2rem',
		textAlign: 'center' as 'center',
		justifyContent: 'center',
		self: 'center',
		alignItems: 'center',
	},
	scheduleTable: {
		width: '100%',
		borderCollapse: 'collapse' as 'collapse',
		backgroundColor: '#444',
		color: '#fff',
		borderRadius: '8px',
		boxShadow: '0 10px 20px rgba(0, 0, 0, 0.3)',
	},
	tableContainer: {
		display: 'flex',
		width: '100%',
	},
	scheduleTableCell: {
		padding: '1.5rem',
		justifyContent: 'center',
		alignItems: 'center',
		textAlign: 'center' as 'center',
		border: '2px solid #555',
		backgroundColor: '#333',
	},
	classBlockCell: {
		backgroundColor: '#666',
		color: '#fff',
		borderRadius: '8px',
		border: '2px solid #444',
		padding: '1rem',
		fontWeight: 'bold',
		justifyContent: 'center',
		alignItems: 'center',
	},
};
